### ISSUE TITLE
Missing instruction to deploy this app

### ISSUE THREAD

**Issue by ajeetraina** [Prathamesh-Shanbhag/EasyApply#1]
Can you please add instructions how to deploy this app? @Prathamesh-Shanbhag

**Comment by Prathamesh-Shanbhag** [comment]
Hey Ajeet Recent Commit has added the instructions to run the app locally but please check the Note mentioned along with it since the entire app was supported by GitHub Jobs API : https://jobs.github.com/api

**Comment by Prathamesh-Shanbhag** [comment]
Please let me know if there is any other issue!
@ajeetraina
